// Italian preset. To use it, replace the content of config/texts.config.js with:
//   export { texts } from './texts.it.js';
// and set language: 'it' in config/site.config.js.
export const texts = {
  landing: {
    heroSubtitle: 'Portfolio fotografico.',
    albumsSectionHeading: 'Album',
  },
  album: {
    notFound: 'Album non trovato.',
    notFoundLink: 'Torna alla gallery',
    loading: 'Caricamento foto…',
    empty: 'Nessuna foto trovata in questo album.',
    error: {
      notFound: 'Album non trovato.',
      network: 'Errore di rete. Controlla la connessione.',
      unknown: 'Errore durante il caricamento. Riprova più tardi.',
      noImage: 'Le immagini non sono disponibili senza un URL pubblico R2.',
    },
  },
  lightbox: {
    label: 'Foto a schermo intero',
    close: 'Chiudi',
    previous: 'Precedente',
    next: 'Successiva',
  },
  about: {
    heading: 'Contatti',
    body: 'Scrivimi per informazioni su lavori e collaborazioni.',
    form: {
      namePlaceholder: 'Nome',
      emailPlaceholder: 'Email',
      subjectPlaceholder: 'Soggetto',
      messagePlaceholder: 'Messaggio',
      submitLabel: 'Invia',
      successMessage: 'Messaggio inviato. Ti risponderò presto.',
      errorMessage: "Errore durante l'invio. Riprova più tardi.",
    },
  },
  footer: {
    copyright: `© ${new Date().getFullYear()}`,
  },
  links: {
    email: 'Email',
    website: 'Sito',
  },
  nav: {
    homeLabel: 'Portfolio',
    aboutLabel: 'Contatti',
  },
  admin: {
    common: {
      loading: 'Caricamento…',
      allAlbums: '← Tutti gli album',
      navAlbums: 'Album',
      navMessages: 'Messaggi',
    },
    site: {
      sectionTitle: 'Sito',
      nameLabel: 'Nome',
      bioLabel: 'Bio',
      instagramLabel: 'Instagram',
      save: 'Salva sito',
      saved: 'Sito salvato.',
      preview: 'Anteprima',
      previewClose: 'Chiudi',
      heroLabel: 'Immagine della home',
      heroUpdated: 'Hero aggiornata.',
      heroReadError: 'Impossibile leggere le foto di questo album.',
      heroChooseAlbum: 'Scegli album…',
      heroNone: 'nessuna',
    },
    albums: {
      sectionTitle: 'Album',
      create: 'Nuovo album',
      newTitlePlaceholder: 'Titolo nuovo album',
      exists: 'Esiste gia un album "{slug}".',
      titleInvalid: 'Titolo non valido.',
      titleReserved: '"{slug}" è un nome riservato.',
      delete: 'Elimina',
      deleteTitle: 'Elimina album',
      deleteNameMismatch: 'Nome non corrispondente: cancellazione annullata.',
      deleteConfirmPrompt: 'Per eliminare scrivi il nome esatto dell\'album: "{titolo}"',
      loadError: 'Impossibile caricare gli album (rete o dati malformati).',
    },
    album: {
      save: 'Salva',
      saved: 'Album salvato.',
      cover: 'Cover',
      coverAsButton: 'Usa come cover',
      coverSelected: 'Cover selezionata: {nome} (premi Salva per confermare).',
      subtitleLabel: 'Sottotitolo',
      subtitlePlaceholder: 'Aggiungi un sottotitolo…',
      gridView: 'Vista griglia',
      listView: 'Vista lista',
      sortBy: 'Ordina per:',
      date: 'Data',
      sortedByDate: 'Foto ordinate per data.',
      confirmDeletePhoto: 'Eliminare {nome}?',
      deletePhoto: 'Elimina',
      manifestError: 'Impossibile caricare il manifest.',
      unsavedChanges: 'Ci sono modifiche non salvate. Uscire comunque?',
      uploadProgress: '{nome} — {fase}',
      uploadPhases: {
        processing: 'compressione',
        uploading: 'caricamento',
        done: 'fatto',
        failed: 'non riuscito',
      },
      uploadSuccess: 'Caricate {n} foto.',
      dropzoneLabel: 'Trascina qui le foto o',
      dropzoneBrowse: 'scegli i file da caricare',
      dropzoneConstraints: 'JPG, PNG, WebP fino a 20MB',
      unsupportedFormat: 'Non caricabili dal browser ({elenco}): HEIC e TIFF vanno convertiti prima, con `npm run compress`.',
      uploadPartial: 'Caricate {uploaded}, fallite {failed}: riprova trascinandole di nuovo.',
    },
    status: {
      lastAction: 'Ultima azione eseguita',
      error: 'Errore',
    },
    messages: {
      sectionTitle: 'Messaggi',
      empty: 'Nessun messaggio ricevuto.',
      loadError: 'Impossibile caricare i messaggi.',
      confirmDelete: 'Eliminare il messaggio di {nome}?',
      deleted: 'Messaggio eliminato.',
      reply: 'Rispondi',
      delete: 'Elimina',
    },
  },
};
