// Interface copy, in English. An Italian version with the same keys is in
// config/texts.it.js: to use it, replace this file's content with
//   export { texts } from './texts.it.js';
// and set language: 'it' in config/site.config.js.
// Placeholders such as {slug} or {nome} are filled by name: keep them as they are.
export const texts = {
  landing: {
    heroSubtitle: 'Photography portfolio.',
    albumsSectionHeading: 'Albums',
  },
  album: {
    notFound: 'Album not found.',
    notFoundLink: 'Back to the gallery',
    loading: 'Loading photos…',
    empty: 'No photos in this album yet.',
    error: {
      notFound: 'Album not found.',
      network: 'Network error. Check your connection.',
      unknown: 'Something went wrong while loading. Please try again later.',
      noImage: 'Images are unavailable without a public R2 URL.',
    },
  },
  lightbox: {
    label: 'Full-screen photo',
    close: 'Close',
    previous: 'Previous',
    next: 'Next',
  },
  about: {
    heading: 'Contact',
    body: 'Write to me about commissions and collaborations.',
    form: {
      namePlaceholder: 'Name',
      emailPlaceholder: 'Email',
      subjectPlaceholder: 'Subject',
      messagePlaceholder: 'Message',
      submitLabel: 'Send',
      successMessage: 'Message sent. I will get back to you soon.',
      errorMessage: 'Something went wrong while sending. Please try again later.',
    },
  },
  footer: {
    copyright: `© ${new Date().getFullYear()}`,
  },
  links: {
    email: 'Email',
    website: 'Website',
  },
  nav: {
    homeLabel: 'Portfolio',
    aboutLabel: 'About',
  },
  admin: {
    common: {
      loading: 'Loading…',
      allAlbums: '← All albums',
      navAlbums: 'Albums',
      navMessages: 'Messages',
    },
    site: {
      sectionTitle: 'Site',
      nameLabel: 'Name',
      bioLabel: 'Bio',
      instagramLabel: 'Instagram',
      save: 'Save site',
      saved: 'Site saved.',
      preview: 'Preview',
      previewClose: 'Close',
      heroLabel: 'Home image',
      heroUpdated: 'Hero updated.',
      heroReadError: 'Could not read the photos of this album.',
      heroChooseAlbum: 'Choose an album…',
      heroNone: 'none',
    },
    albums: {
      sectionTitle: 'Albums',
      create: 'New album',
      newTitlePlaceholder: 'New album title',
      exists: 'An album "{slug}" already exists.',
      titleInvalid: 'Invalid title.',
      titleReserved: '"{slug}" is a reserved name.',
      delete: 'Delete',
      deleteTitle: 'Delete album',
      deleteNameMismatch: 'The name does not match: deletion cancelled.',
      deleteConfirmPrompt: 'To delete, type the exact album name: "{titolo}"',
      loadError: 'Could not load the albums (network or malformed data).',
    },
    album: {
      save: 'Save',
      saved: 'Album saved.',
      cover: 'Cover',
      coverAsButton: 'Use as cover',
      coverSelected: 'Cover selected: {nome} (press Save to confirm).',
      subtitleLabel: 'Subtitle',
      subtitlePlaceholder: 'Add a subtitle…',
      gridView: 'Grid view',
      listView: 'List view',
      sortBy: 'Sort by:',
      date: 'Date',
      sortedByDate: 'Photos sorted by date.',
      confirmDeletePhoto: 'Delete {nome}?',
      deletePhoto: 'Delete',
      manifestError: 'Could not load the photo list.',
      unsavedChanges: 'There are unsaved changes. Leave anyway?',
      uploadProgress: '{nome} — {fase}',
      uploadPhases: {
        processing: 'compressing',
        uploading: 'uploading',
        done: 'done',
        failed: 'failed',
      },
      uploadSuccess: 'Uploaded {n} photos.',
      dropzoneLabel: 'Drop photos here or',
      dropzoneBrowse: 'choose files to upload',
      dropzoneConstraints: 'JPG, PNG, WebP up to 20MB',
      unsupportedFormat: 'The browser cannot upload these ({elenco}): convert HEIC and TIFF first, with `npm run compress`.',
      uploadPartial: 'Uploaded {uploaded}, failed {failed}: try again by dropping them once more.',
    },
    status: {
      lastAction: 'Last action',
      error: 'Error',
    },
    messages: {
      sectionTitle: 'Messages',
      empty: 'No messages yet.',
      loadError: 'Could not load the messages.',
      confirmDelete: 'Delete the message from {nome}?',
      deleted: 'Message deleted.',
      reply: 'Reply',
      delete: 'Delete',
    },
  },
};
