// Italian preset. To use it, replace the content of config/texts.config.js with:
//   export { texts } from './texts.it.js';
// and set language: 'it' in config/site.config.js.
export const texts = {
  landing: {
    heroSubtitle: 'Portfolio fotografico.',
    albumsSectionHeading: 'Album',
  },
  album: {
    notFound: 'Album non trovato.',
    notFoundLink: 'Torna alla gallery',
    loading: 'Caricamento foto…',
    empty: 'Nessuna foto trovata in questo album.',
    error: {
      notFound: 'Album non trovato.',
      network: 'Errore di rete. Controlla la connessione.',
      unknown: 'Errore durante il caricamento. Riprova più tardi.',
      noImage: 'Le immagini non sono disponibili senza un URL pubblico R2.',
    },
  },
  lightbox: {
    label: 'Foto a schermo intero',
    close: 'Chiudi',
    previous: 'Precedente',
    next: 'Successiva',
  },
  about: {
    heading: 'Contatti',
    body: 'Scrivimi per informazioni su lavori e collaborazioni.',
    form: {
      namePlaceholder: 'Nome',
      emailPlaceholder: 'Email',
      subjectPlaceholder: 'Soggetto',
      messagePlaceholder: 'Messaggio',
      submitLabel: 'Invia',
      successMessage: 'Messaggio inviato. Ti risponderò presto.',
      errorMessage: "Errore durante l'invio. Riprova più tardi.",
    },
  },
  footer: {
    copyright: `© ${new Date().getFullYear()}`,
  },
  links: {
    email: 'Email',
    website: 'Sito',
  },
  preview: {
    unavailable: 'Anteprima non disponibile: entra nella dashboard, poi riapri l\'anteprima.',
  },
  nav: {
    homeLabel: 'Portfolio',
    aboutLabel: 'Contatti',
  },
  admin: {
    common: {
      loading: 'Caricamento…',
      allAlbums: '← Tutti gli album',
      navAlbums: 'Album',
      navMessages: 'Messaggi',
      navSite: 'Sito',
      navLabel: 'Sezioni della dashboard',
      loadError: 'Impossibile caricare la dashboard. Controlla la connessione e ricarica la pagina.',
    },
    publish: {
      changesOne: '1 modifica',
      changesMany: '{n} modifiche',
      preview: 'Anteprima',
      publish: 'Pubblica',
      regionLabel: 'Pubblicazione',
      resume: 'Riprendi la pubblicazione',
      publishing: 'Pubblicazione…',
      photosLeft: 'Pubblicazione… mancano {n} foto',
      published: 'Pubblicato.',
      allPublished: 'Tutto pubblicato',
      draftSaved: 'Bozza salvata',
      discard: 'Annulla le modifiche',
      discardTitle: 'Annullare tutte le modifiche?',
      discardBody: 'La bozza e le foto in attesa di pubblicazione vengono cancellate. Il sito resta com\'è.',
      discardConfirm: 'Annulla le modifiche',
      discarded: 'Modifiche annullate.',
      cancel: 'Indietro',
      inProgress: 'Una pubblicazione è iniziata: completala con Pubblica.',
      problemsTitle: 'Non ancora pubblicato: prima sistema questi punti.',
      problemPhotoMissing: '{album}: manca la foto {name}.',
      problemCover: '{album}: la copertina {name} non è nell\'album.',
      problemHero: 'L\'immagine della home {name} non è nell\'album {album}.',
      failed: 'Pubblicazione interrotta: {message}. Premi Pubblica per riprendere.',
      noProgress: 'La pubblicazione non va avanti. Riprova tra qualche minuto.',
      saving: 'Salvataggio…',
      waitingPublication: 'Le modifiche aspettano la pubblicazione',
      saveFailed: 'Non salvato: {message}',
      retry: 'Riprova',
      changesTitle: 'Cosa cambia pubblicando',
      close: 'Chiudi',
      changeSite: 'Nome, bio, link o testi delle pagine',
      changeAlbumsReordered: 'Album in un nuovo ordine',
      changeAlbumAdded: 'Nuovo album: {album}',
      changeAlbumRemoved: 'Album eliminato: {album}',
      changeAlbumChanged: 'Album modificato: {album}',
      changePhotosAdded: '{album}: {n} foto nuove',
      changePhotosRemoved: '{album}: {n} foto tolte',
      changePhotosReordered: '{album}: foto in un nuovo ordine',
    },
    site: {
      sectionTitle: 'Sito',
      nameLabel: 'Nome',
      bioLabel: 'Bio',
      instagramLabel: 'Instagram',
      save: 'Salva sito',
      saved: 'Sito salvato.',
      preview: 'Anteprima',
      previewClose: 'Chiudi',
      heroLabel: 'Immagine della home',
      heroUpdated: 'Hero aggiornata.',
      heroReadError: 'Impossibile leggere le foto di questo album.',
      heroChooseAlbum: 'Scegli album…',
      heroNone: 'nessuna',
    },
    albums: {
      sectionTitle: 'Album',
      create: 'Nuovo album',
      newTitlePlaceholder: 'Titolo nuovo album',
      exists: 'Esiste gia un album "{slug}".',
      titleInvalid: 'Titolo non valido.',
      titleReserved: '"{slug}" è un nome riservato.',
      delete: 'Elimina',
      deleteTitle: 'Elimina album',
      deleteNameMismatch: 'Nome non corrispondente: cancellazione annullata.',
      deleteConfirmPrompt: 'Per eliminare scrivi il nome esatto dell\'album: "{titolo}"',
      loadError: 'Impossibile caricare gli album (rete o dati malformati).',
      titleLabel: 'Titolo',
      createConfirm: 'Crea',
      cancel: 'Annulla',
      empty: 'Ancora nessun album: crea il primo.',
      photoCountNone: 'Ancora nessuna foto',
      photoCountOne: '1 foto',
      photoCountMany: '{n} foto',
      reorder: 'Riordina',
      reorderDone: 'Fatto',
      moveEarlier: 'Sposta {album} prima',
      moveLater: 'Sposta {album} dopo',
      reorderHint: 'Trascina gli album, o usa le frecce: l\'ordine è quello del sito.',
    },
    album: {
      save: 'Salva',
      saved: 'Album salvato.',
      cover: 'Cover',
      coverAsButton: 'Usa come cover',
      coverSelected: 'Cover selezionata: {nome} (premi Salva per confermare).',
      subtitleLabel: 'Sottotitolo',
      subtitlePlaceholder: 'Aggiungi un sottotitolo…',
      gridView: 'Vista griglia',
      listView: 'Vista lista',
      sortBy: 'Ordina per:',
      date: 'Data',
      sortedByDate: 'Foto ordinate per data.',
      confirmDeletePhoto: 'Eliminare {nome}?',
      deletePhoto: 'Elimina',
      manifestError: 'Impossibile caricare il manifest.',
      unsavedChanges: 'Ci sono modifiche non salvate. Uscire comunque?',
      uploadProgress: '{nome} — {fase}',
      uploadPhases: {
        processing: 'compressione',
        uploading: 'caricamento',
        done: 'fatto',
        failed: 'non riuscito',
      },
      uploadSuccess: 'Caricate {n} foto.',
      dropzoneLabel: 'Trascina qui le foto o',
      dropzoneBrowse: 'scegli i file da caricare',
      dropzoneConstraints: 'JPG, PNG, WebP fino a 20MB',
      unsupportedFormat: 'Non caricabili dal browser ({elenco}): HEIC e TIFF vanno convertiti prima, con `npm run compress`.',
      uploadPartial: 'Caricate {uploaded}, fallite {failed}: riprova trascinandole di nuovo.',
      titleLabel: 'Titolo',
      titleRequired: 'Il titolo non può essere vuoto: resta l\'ultimo.',
      notFound: 'Questo album non è nella bozza.',
      empty: 'Ancora nessuna foto: carica le prime.',
      photoLabel: 'Foto {n}',
      coverBadge: 'Copertina',
      movePhotoEarlier: 'Sposta la foto {n} prima',
      movePhotoLater: 'Sposta la foto {n} dopo',
      deletePhotoBody: 'Sparisce dal sito quando pubblichi.',
      deleteAlbum: 'Elimina l\'album',
      deleteAlbumTitle: 'Eliminare «{album}»?',
      deleteAlbumBody: 'L\'album e le sue foto spariscono dal sito quando pubblichi.',
      upload: 'Carica foto',
      uploadFailedItem: '{nome}: {motivo}',
      uploadWaits: 'I caricamenti aspettano la fine della pubblicazione.',
      dropHere: 'Rilascia le foto per caricarle',
      dropHint: 'Puoi anche trascinare qui le foto',
      cancel: 'Annulla',
    },
    status: {
      lastAction: 'Ultima azione eseguita',
      error: 'Errore',
    },
    messages: {
      sectionTitle: 'Messaggi',
      empty: 'Nessun messaggio ricevuto.',
      loadError: 'Impossibile caricare i messaggi.',
      confirmDelete: 'Eliminare il messaggio di {nome}?',
      deleted: 'Messaggio eliminato.',
      reply: 'Rispondi',
      delete: 'Elimina',
    },
  },
};
